//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForum.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cmt_BaiViet
    {
        public int ID { get; set; }
        public Nullable<int> IDBaiViet { get; set; }
        public string IDNguoiCmt { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> isCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<bool> isXoa { get; set; }
        public string IDNguoiXoa { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual BaiViet BaiViet { get; set; }
    }
}
