//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForum.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int ID { get; set; }
        public Nullable<int> IDBaiViet { get; set; }
        public string IDNguoiNhanThongBao { get; set; }
        public Nullable<int> LoaiThongBao { get; set; }
        public Nullable<System.DateTime> NgayTaoThongBao { get; set; }
        public string NoiDungThongBao { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual BaiViet BaiViet { get; set; }
    }
}
